config/routes.rb
Rails.application.routes.draw do
  # Scope manages languages
  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
    # Only for logged-in users
    devise_for :users
    authenticate :user do
      resources :videos, except: [:index, :show]
      resources :articles, except: [:index, :show]
      resources :items, except: [:index, :show]
    end

    # Public stuff
    resources :videos, only: [:index, :show]
    resources :articles, only: [:index, :show]
    resources :items, only: [:index, :show]
    get :vocabulary, to: redirect("http://kanjirpg.com/en/vocabulary", status: 302)
    get :proverbs, to: redirect("http://kanjirpg.com/en/proverbs", status: 302)
    get :idioms, to: redirect("http://kanjirpg.com/en/idioms", status: 302)
    get :ateji, to: redirect("http://kanjirpg.com/en/ateji", status: 302)
    get :about, to: redirect("http://kanjirpg.com/en/about", status: 302)

    # Main page
    root to: 'welcomes#index'

    # All other routes are an error, they go home
    get '*path', to: redirect("http://kanjirpg.com/en", status: 302)
  end

  # Redirect to language
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  get '/*path', to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: { path: /(?!(#{I18n.available_locales.join('|')})\/).*/ }, format: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_attached_file :image, styles: {
    small: '100x100>',
    medium: '500x500>',
    large: '1000x1000>'
  }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/item.rb
class Item < ApplicationRecord
  is_impressionable counter_cache: true

  include SearchCop
  search_scope :search do
    attributes :category
  end

  def to_param
    self.slug
    self.id
  end
  before_save :create_slug

  private
    def create_slug
      self.slug = self.word.downcase.strip.gsub(' ', '-')
    end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :remove_www_subdomain

  protect_from_forgery with: :exception

  before_action :set_locale

  helper_method :switch_language_path, :current_path_new_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  def current_path_new_locale(new_locale)
    locale = I18n.default_locale
    I18n.available_locales.each do |lan|
      if new_locale == lan
        locale = "/#{lan}"
      end
    end
    request.path.sub(/\/(#{I18n.available_locales.join('|')})/, locale)
  end

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def remove_www_subdomain
    if /^www/.match(request.host)
      redirect_to("#{request.protocol}busensei.com#{request.fullpath}", :status => 301)
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :time_zone, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :time_zone, :email, :password, :current_password])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]

  def index
    @articles = Article.order("created_at DESC")
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :image, :blurb)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all.order(:reading).page(params[:page])
  end

  def vocabulary
    @items = Item.all.search("category: 'Vocab'").order(:reading).page(params[:page])
  end

  def proverbs
    @items = Item.all.search("category: 'kotowaza'").order(:reading).page(params[:page])
  end

  def idioms
    @items = Item.all.search("category: 'yjjg'").order(:reading).page(params[:page])
  end

  def ateji
    @items = Item.all.search("category: 'ateji'").order(:reading).page(params[:page])
  end

  def show
    impressionist @item, unique: [:session_hash]
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
    def set_item
      @item = Item.find_by(slug: params[:id])
      @item = Item.find(params[:id]) if !@item
      redirect_to "http://kanjirpg.com/en/items/#{@item.slug}"
    end
    def item_params
      params.require(:item).permit(:word, :reading, :english, :notes, :synonyms, :opposites, :found_in, :japanese, :origin, :test, :level, :category, :slug)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all.order(created_at: :desc)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_video
    @video = Video.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def video_params
    params.require(:video).permit(:title, :tag)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
    @vocabulary = Item.search("category: 'Vocab'").order('impressions_count DESC').take(4)
    @proverbs = Item.search("category: 'kotowaza'").order('impressions_count DESC').take(4)
    @idioms = Item.search("category: 'yjjg'").order('impressions_count DESC').take(4)
    @ateji = Item.search("category: 'ateji'").order('impressions_count DESC').take(4)
    @videos = Video.last(1)
    @articles = Article.last(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/articles/_form.html.haml
= simple_form_for(@article, multipart: true) do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg
  = f.input :title
  = f.input :image, as: :file
  = f.input :blurb, as: :text
  = f.button :submit

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1
  %span.mdi.mdi-cards
  Blog
%br
- if user_signed_in?
  = link_to 'New Article', new_article_path, class: 'btn btn-success'
  %br
  %br
- @articles.each_slice(5) do |row|
  .row
    - row.each do |article|
      .col-sm-2
        = link_to article do
          .card
            .card-header
              = article.title
            .card-block
              = image_tag article.image.url(:small), class: 'img-fluid rounded'
              - if user_signed_in?
                %br
                = link_to 'Edit', edit_article_path(article), class: 'btn btn-secondary'
                = link_to 'Delete', article, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

app/views/articles/new.html.haml
%h1 New Article
= render 'form'

app/views/articles/show.html.haml
%h1= @article.title
= image_tag @article.image.url(:large)
%p= simple_format @article.blurb

- if user_signed_in?
  = link_to 'Edit', edit_article_path(@article), class: 'btn btn-secondary'

app/views/items/_form.html.haml
= simple_form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-sm-6
      = f.input :key
      %p It is extremely important that the key is unique
      = f.input :word
      = f.input :reading, as: :text
      = f.input :english, as: :text
      = f.input :notes, as: :text
      = f.input :synonyms
      = f.input :opposites
    .col-sm-6
      = f.input :found_in
      = f.input :japanese, as: :text
      = f.input :origin, as: :text
      = f.input :test
      = f.input :level
      = f.input :category
      = f.button :submit

app/views/items/_results.html.haml
.card.mb-2
  .card-block
    .row
      .col-sm-4
        %h1
          ぶ先生
        %p
          %span.mdi.mdi-book-open-page-variant
          = t('shared.navbar.study_materials')
          %br
          %span.mdi{class: "mdi-#{icon}"}
          = title
      .col-sm-8
        %h1 &nbsp;
        %p= intro
        - if user_signed_in?
          = link_to 'New Item',
                    new_item_path,
                    class: 'btn btn-success'
= paginate items, theme: 'twitter-bootstrap-4'
.row#masonry
  - items.each_slice(4) do |four|
    .clearfix
    - four.each_slice(2) do |two|
      .clearfix.hidden-xl-up
      - two.each do |item|
        .col-xl-3.col-sm-6
          = render partial: 'shared/card',
                   locals: { item: item }
= paginate items, theme: 'twitter-bootstrap-4'

app/views/items/ateji.html.haml
= render partial: 'results', locals: { items: @items, icon: 'shuffle', title: t('actions.ateji'), intro: t('.intro') }

app/views/items/edit.html.haml
%h1 Editing DB entry
= render 'form'
= link_to 'Show', @item

app/views/items/idioms.html.haml
= render partial: 'results', locals: { items: @items, icon: 'cat', title: t('actions.idioms'), intro: t('.intro') }

app/views/items/index.html.haml
= render partial: 'results', locals: { items: @items, icon: 'database', title: t('actions.all_items'), intro: t('.intro') }

app/views/items/new.html.haml
%h1 Add new entry to DB
= render 'form'

app/views/items/proverbs.html.haml
= render partial: 'results', locals: { items: @items, icon: 'duck', title: t('actions.proverbs'), intro: t('.intro') }

app/views/items/show.html.haml
= render partial: 'shared/card', locals: { item: @item }
-# Edit button
- if user_signed_in?
  = link_to 'Edit', edit_item_path(@item)

app/views/items/vocabulary.html.haml
= render partial: 'results', locals: { items: @items, icon: 'dictionary', title: t('actions.vocabulary'), intro: t('.intro') }

app/views/layouts/application.haml
!!! 5
%html{lang: I18n.locale}
  %head
    %meta{"http-equiv" => "Content-Type", :content => "text/html;charset=utf-8"}
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no'}
    %meta{:'http-equiv' => 'x-ua-compatible', content: 'ie=edge'}
    = csrf_meta_tags
    %title= t('seo.brand')
    %meta{name: 'description', content: t('seo.description')}
    %meta{name: "google", content: "notranslate"}
    %meta{name: 'author', content: t('seo.author')}
    %meta{name: 'keywords', content: t('seo.keywords')}

    %link{href: "/apple-icon-57x57.png", rel: "apple-touch-icon", sizes: "57x57"}
    %link{href: "/apple-icon-60x60.png", rel: "apple-touch-icon", sizes: "60x60"}
    %link{href: "/apple-icon-72x72.png", rel: "apple-touch-icon", sizes: "72x72"}
    %link{href: "/apple-icon-76x76.png", rel: "apple-touch-icon", sizes: "76x76"}
    %link{href: "/apple-icon-114x114.png", rel: "apple-touch-icon", sizes: "114x114"}
    %link{href: "/apple-icon-120x120.png", rel: "apple-touch-icon", sizes: "120x120"}
    %link{href: "/apple-icon-144x144.png", rel: "apple-touch-icon", sizes: "144x144"}
    %link{href: "/apple-icon-152x152.png", rel: "apple-touch-icon", sizes: "152x152"}
    %link{href: "/apple-icon-180x180.png", rel: "apple-touch-icon", sizes: "180x180"}
    %link{href: "/android-icon-192x192.png", rel: "icon", sizes: "192x192", :type => "image/png"}
    %link{href: "/favicon-32x32.png", rel: "icon", sizes: "32x32", :type => "image/png"}
    %link{href: "/favicon-96x96.png", rel: "icon", sizes: "96x96", :type => "image/png"}
    %link{href: "/favicon-16x16.png", rel: "icon", sizes: "16x16", :type => "image/png"}
    %link{href: "/manifest.json", rel: "manifest"}
    %meta{content: "#00b9b3", name: "msapplication-TileColor"}
    %meta{content: "/ms-icon-144x144.png", name: "msapplication-TileImage"}
    %meta{content: "#00b9b3", name: "theme-color"}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  %body{id: params[:controller], class: params[:action]}
    .wrapper
      = render partial: 'shared/navbar'
      = render partial: 'shared/flash'
      .alert.alert-danger
        - if I18n.locale == :ja
          %b お知らせ!
          サイトを移動しました→
        - else
          %b Attention!
          My database and learning materials have moved to a new site:
        %a{href: "http://kanjirpg.com", alt: 'kanjiRPG'} kanjiRPG
      %br
      .container-fluid
        = yield
        %br
        %br
      .push
    .footer
      = render partial: 'shared/footer'

app/views/shared/_card.html.haml
= render partial: 'shared/snippet',
         locals: { item: item }
.card#kanji
  .card-block
    .row
      .col-xs-6
        - if item.category
          %p
            - if item.category    == 'Vocab'
              %span.mdi.mdi-dictionary
              Vocabulary
            - elsif item.category == 'kotowaza'
              %span.mdi.mdi-duck
              Proverb
            - elsif item.category == 'yjjg'
              %span.mdi.mdi-cat
              Idiom
            - elsif item.category == 'ateji'
              %span.mdi.mdi-shuffle
              Ateji
            - else
              %span.mdi.mdi-database
              Other
        - if item.reading
          %p
            = item.reading.gsub(':', '<br>').gsub(';', '<br>').gsub('②', '<br>②').gsub('①', '<br>①').html_safe
        - if item.english
          %p
            = item.english.gsub(':', '<br>').gsub(';', '<br>').gsub('②', '<br>②').gsub('①', '<br>①').html_safe
      .col-xs-6
        = link_to item do
          - if item.word
            %h1.vertical-rl.float-xs-right
              - if item.word.length == 4 || item.word.length > 8
                - count = item.word.length / 2
                %span><= item.word[0..(count - 1)]
                %br
                %span><= item.word[count..item.word.length]
              - else
                .max-height
                  %span><= item.word.gsub(', ', '<br>').gsub('、', '<br>').html_safe
    - if user_signed_in?
      = link_to 'Edit',
                edit_item_path(item)
      = link_to 'Destroy',
                item,
                method: :delete,
                data: { confirm: 'Are you sure?' }

app/views/shared/_flash.haml
- if flash
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      .alert.alert-default.animated.fadeInDown.delay.col-sm-6.offset-sm-3#flash{class: "alert-#{name == 'notice' ? 'info' : 'success'}"}
        %a.close{'data-dismiss' => 'alert'}
          &times;
        = content_tag :div, msg, :id => "flash_#{name}"

app/views/shared/_footer.haml
%footer.text-xs-center
  .container-fluid.m-t-3.m-b-1
    Copyright
    - if user_signed_in?
      = link_to '©', destroy_user_session_path, method: :delete
    - else
      = link_to '©', new_user_session_path
    2016 Bret Mayer

app/views/shared/_navbar.haml
%nav.navbar.navbar-top.navbar-light.bg-faded
  %ul.nav.nav-pills.float-md-left
    %li.nav-item
      = link_to root_path, class: 'nav-link text-primary' do
        %span.mdi.mdi-book-open-page-variant
        = t('.brand')
  %ul.nav.nav-pills.float-md-right
    %li.nav-item
      = link_to articles_path, class: 'nav-link' do
        %span.mdi.mdi-cards
        = t('.articles')
    %li.nav-item
      = link_to videos_path, class: 'nav-link' do
        %span.mdi.mdi-video
        = t('.videos')
    %li.nav-item
      - if I18n.locale == :en
        = link_to content_tag(:span, '', class:'mdi mdi-translate') + ' 日本語', current_path_new_locale('ja'.to_sym), class: 'nav-link'
      - else
        = link_to content_tag(:span, '', class:'mdi mdi-translate') + ' English', current_path_new_locale('en'.to_sym), class: 'nav-link'

app/views/shared/_snippet.html.haml
-# Google Snippet
%script{:type => "application/ld+json"}
  {
  "@context": "http://schema.org/",
  "@type": "Thing",
  "name": "#{item.word}",
  "alternatename": "#{item.reading}",
  "description": "#{item.english}"
  }

app/views/videos/_form.html.haml
= simple_form_for @video do |f|
  - if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |msg|
          %li= msg
  = f.input :title
  %p Title can be anything
  = f.input :tag
  %p The tag is the identifier of the YouTube video
  = f.button :submit

app/views/videos/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
%h1
  %span.mdi.mdi-video
  Videos
%br
- if user_signed_in?
  = link_to 'New Video', new_video_path, class: 'btn btn-success'
  %br
  %br
- @videos.each_slice(3) do |row|
  .row
    - row.each do |video|
      .col-sm-4
        = link_to video do
          .card
            %h5.card-header
              = video.title
            .card-block
              .embed-responsive.embed-responsive-16by9
                %iframe{allowfullscreen: "", src: "https://www.youtube.com/embed/#{video.tag}", class: 'embed-responsive-item'}
              - if user_signed_in?
                %br
                = link_to 'Edit', edit_video_path(video), class: 'btn btn-secondary'
                = link_to 'Destroy', video, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-secondary'

app/views/videos/new.html.haml
%h1 Add new Video
= render 'form'

app/views/videos/show.html.haml
%h1= @video.title
.embed-responsive.embed-responsive-16by9
  %iframe{allowfullscreen: "", src: "https://www.youtube.com/embed/#{@video.tag}", class: 'embed-responsive-item'}
- if user_signed_in?
  = link_to 'Edit', edit_video_path(@video)